'''fibonacci is a method in which a new number is generated by
    adding the last two numbers
    eg: [1,2,3,5,8,13,21.....]
'''

#Date: April 4th, 2019

def fibonacci():
    ans=[] #this list stores the generated values
    x=int(input("X: ")) #starting number
    y=int(input("Y: ")) #second number
    ans.append(x)
    ans.append(y)
    length=int(input("Till Number: "))
    while ans[-1]<=length:   #loop
        z=ans[-1]+ans[-2]   #taking the last two numbers and then adding both of them
        ans.append(z)   #ammending the new integer created
    print(ans)
